name: Continuous Delivery

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-toolbox:
    name: Build Toolbox
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            plat-name-simple: linux
            target-path: ./build/*.AppImage
          - os: macos-latest
            plat-name-simple: macos
            target-path: ./build/*.dmg
          - os: windows-latest
            plat-name-simple: windows
            target-path: ./build/*.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Aries Toolbox
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && github.repository == 'hyperledger/aries-toolbox'
        with:
          name: ${{matrix.plat-name-simple}}
          path: ${{matrix.target-path}}
